### ISSUE TITLE
Remote completion of gaspi_write

### ISSUE THREAD

**Issue by harryherold** [cc-hpc-itwm/GPI-2#22]
Is it possible to support a remote completion mechanism for the caller of the gaspi_write like MPI_Win_flush ?

**Comment by csimmend** [comment]
Hi 

Not sure i understand this question ?

write + subsequent notify = remote completion 
This is a fine grain remote completion per local queue and remote  rank/segment.
Alternatively you would use a single write_notify.

wait for local completion at source is done via gaspi_wait(queue)
this waits for all local completions in that queue.

mpi_win_flush in contrast does local completion and enforces remote completion - however 
the remote target won't know about the remote completion until you issue a subsequent accumulate (or similar).

so the gaspi semantics reads
write_notify() // waiting for neither local nor remote completion

and MPI semantics reads
mpi_win_flush() // wait for local and remote completion
mpi_accumulate()

**Comment by harryherold** [comment]
We need a function to wait on remote completion for the caller of gaspi_write(sender).
e.g.
```
gaspi_write(rank=1, queue=1,..);
// fictional function for remote completion
gaspi_flush(rank=1, queue=1);
```
the same code in MPI:
```
MPI_Put(rank=1,win);
MPI_Win_flush(rank, win);
```
I know there is actually no function like ```gaspi_flush``` but is it possible to implement it in  GPI2 ?

**Comment by csimmend** [comment]
in GASPI remote completion == "notification is visible remotely".
In that sense MPI_Win_flush != "remote completion". 

I assume what you really aim for is not remote completion, but rather local completion ?
if correct: queue_wait() will wait for local completion. 

However - in terms of performance calling queue_wait() is almost as bad as 
MPI_Win_flush. In both cases (queue_wait and MPI_Win_flush, this waits/blocks until Elvis has left the building. (entirely, all writes in the queue (GASPI) / all puts (MPI)) 

GASPI waits for single queue, MPI_Win_flush will wait for everything.

**Comment by mrahn** [comment]
The `gaspi_flush` would be a two sided operation. You can implement the desired behavior in GASPI:

on the local node
```
gaspi_write_notify (..., notification_id, value=notification_id_ack);
gaspi_waitsome (..., notification_id_ack, ...);
```

on the remote node run a thread like
```
while (true)
{
  gaspi_waitsome (..., possible_notifications_to_be_acked, &notified, ...);
  gaspi_reset (notified, &value);
  gaspi_notify (sender (notified), notification_id=value, ...);
}
```

Yes, this introduces an active component. I can not see at the moment how this could be avoided. Note that there is management of notification id's involved, basically distinct ranges of notification id's per rank are required.

So my question is: Can you give more details on your usage scenario? Why is it important for the local progress to know about the remote completion, rather then the local completion (`gaspi_wait`)? Isn't that a race always? (Because what can be concluded from that knowledge?)

Are you going to report the validity of the remote buffer to some third entity? And why isn't the remote node doing that report?

**Comment by harryherold** [comment]
A two-sided ```gaspi_flush``` doesn't match, we need a one-sided variant.
In my opinion ```*_flush`` operation is useless, but in our project we have the
following case:

**Comment by csimmend** [comment]
i see. <code> gaspi_write </code>
So yes , the MPI_Win_flush would work, whereas

**Comment by mrahn** [comment]
No, `write(); wait(); read()` does not guarantee that the `read()` reads the data written by the `write()`. The `wait()` tells something about the local buffer, not the remote one. With Infiniband you probably never will observe wrong data, with Ethernet you will. (Been there and ended up with the solution sketched above.)

I do not know about a single sided solution to wait for remote completion.

**Comment by krzikalla** [comment]
flush is too brutal. What we need for this case is just a ordering construct - a fence. openShmem already has it. 
Question is, whether it can be implemented efficiently on all platforms. Maybe we can impose fences to a particular queue only. This could make it a no-op on platforms with non-overtaking messages.

**Comment by csimmend** [comment]
Ordering in GASPI should be bound to notifications, i believe. 
I was suggesting reading remote notifications lately.  More than a fence, less than a flush.

    gaspi_write_notify(rank)
    do  {
      res = gaspi_query_notifiy(rank);
    } while (res != SUCCESS);
    gaspi_read();

In contrast to a fence this would also work with A writes to B, C reads from B.
Still time to submit proposal. Deadline is 4th of Jan. :-)

**Comment by harryherold** [comment]
Guarantee a ordering is a good idea!

**Comment by csimmend** [comment]
not sure on the shmem "fence". Essentially fence relates to ordering subsequent puts. (and that again is the core of gaspi_write_notify (where the latter allows for somewhat better optimization, depending on HW, simply because its all rolled into a single call). For put/get ordering the correct procedure would be "quiet". And that is an entirely different beast ... presumably we talk about a flush here as well.
